/**
 * zegoVideoService.js
 * Wraps @zegocloud/zego-uikit-prebuilt to provide a stable interface.
 *
 * SECURITY: The Server Secret NEVER touches the frontend.
 * All tokens are generated by the backend at /api/video/token.
 * The frontend receives only a short-lived token.
 *
 * To swap video providers in the future:
 *   - Replace the implementation below
 *   - Keep the exported interface identical
 */

import { ZegoUIKitPrebuilt } from '@zegocloud/zego-uikit-prebuilt'
import { apiUrl } from '../../services/apiBase'

const APP_ID   = parseInt(import.meta.env.VITE_ZEGO_APP_ID || '0', 10)

/**
 * Build a stable, ZEGOCLOUD-safe room ID from a consultation ID.
 * Rules: max 128 chars, only a-z A-Z 0-9 _ -
 */
export function buildRoomId(consultationId) {
  return `consultation_${consultationId}`.replace(/[^a-zA-Z0-9_-]/g, '-').slice(0, 128)
}

/**
 * Build a stable user ID from a role + consultation ID.
 */
export function buildUserId(role, consultationId) {
  return `${role}-${consultationId}`.replace(/[^a-zA-Z0-9_-]/g, '-').slice(0, 64)
}

/**
 * Fetch a secure token from the backend.
 * The backend holds the Server Secret and returns only the generated token.
 */
async function fetchToken(roomId, userId, userName) {
  const params = new URLSearchParams({ roomId, userId, userName })
  const res    = await fetch(`${apiUrl('/api/video/token')}?${params}`)
  if (!res.ok) {
    const body = await res.json().catch(() => ({}))
    throw new Error(body.message || `Token request failed (HTTP ${res.status})`)
  }
  const data = await res.json()
  if (!data.success || !data.token) {
    throw new Error(data.message || 'Invalid token response from server.')
  }
  const appId = Number(data.appId || APP_ID)
  console.log('[ZEGO]', new Date().toISOString(), 'token response', {
    appId,
    roomId,
    userId,
    tokenExists: !!data.token,
    tokenLength: data.token?.length,
    tokenPrefix: data.token?.slice(0, 10),
  })
  return { token: data.token, appId }
}

/**
 * Create a ZEGOCLOUD UIKit Prebuilt kit token.
 * Always uses backend token generation — Server Secret never reaches the browser.
 */
export async function createKitToken({ roomId, userId, userName }) {
  if (!APP_ID) {
    throw new Error(
      'ZEGOCLOUD App ID is not configured.\n' +
      'Please set VITE_ZEGO_APP_ID in your .env file.\n' +
      'Get your App ID from https://console.zegocloud.com'
    )
  }

  const { token, appId } = await fetchToken(roomId, userId, userName)
  const kitToken = ZegoUIKitPrebuilt.generateKitTokenForProduction(
    Number(appId),
    token,
    roomId,
    userId,
    userName,
  )
  console.log('[ZEGO]', new Date().toISOString(), 'kitToken created', {
    appId: Number(appId),
    roomId,
    userId,
    kitTokenExists: !!kitToken,
    kitTokenLength: kitToken?.length,
    kitTokenPrefix: typeof kitToken === 'string' ? kitToken.slice(0, 10) : null,
  })
  return kitToken
}

/**
 * isConfigured — returns true if the App ID is set.
 * The actual Server Secret is validated by the backend when /api/video/token is called.
 */
export function isZegoConfigured() {
  return APP_ID > 0
}
